// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"about-page\"><!-- Hero --><div class=\"about-page-hero dot-bg\"><div class=\"about-page-hero-inner\"><div class=\"hero-eyebrow\">IDENTITY FILE</div><h1 class=\"hero-name\" data-text=\"DESAI\"><span class=\"stroke\">DE</span><span class=\"filled\">SAI</span> <span class=\"small-line\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("// WHO AM I")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/about.templ`, Line: 11, Col: 45}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></h1></div></div><!-- About strip --><section class=\"about-strip\"><div class=\"about-inner\"><div><div class=\"about-label\">Identity</div><div class=\"about-heading\">КТО<br>Я ТАКОЙ</div><p class=\"about-text\">Чувак который что-то делает. Пишу бэкенд на Go, иногда ломаю фронтенд, читаю маньяков от программирования и делюсь мыслями здесь.<br><br>Этот блог — мой цифровой след. Без рекламы, без трекинга. Только то что я реально думаю и делаю.</p></div><div><div class=\"about-label\">Stack</div><div class=\"about-heading\">ЧЕМ<br>ЗАНЯТ</div><ul class=\"skill-list\"><li class=\"skill-item\"><div class=\"skill-name\"><span>GO / BACKEND</span><span class=\"skill-pct\">30%</span></div><div class=\"skill-bar-bg\"><div class=\"skill-bar\" style=\"width:90%\"></div></div></li><li class=\"skill-item\"><div class=\"skill-name\"><span>SYSTEMS / LINUX</span><span class=\"skill-pct\">30%</span></div><div class=\"skill-bar-bg\"><div class=\"skill-bar green\" style=\"width:80%\"></div></div></li><li class=\"skill-item\"><div class=\"skill-name\"><span>WEB / FRONTEND</span><span class=\"skill-pct\">5%</span></div><div class=\"skill-bar-bg\"><div class=\"skill-bar\" style=\"width:65%\"></div></div></li><li class=\"skill-item\"><div class=\"skill-name\"><span>HTMX / TEMPL</span><span class=\"skill-pct\">20%</span></div><div class=\"skill-bar-bg\"><div class=\"skill-bar\" style=\"width:75%\"></div></div></li></ul></div><div><div class=\"about-label\">Links</div><div class=\"about-heading\">СВЯЗЬ</div><div class=\"contact-items\"><a href=\"https://github.com/desaidread\" class=\"contact-item\"><div class=\"contact-icon\">GH</div><div><span class=\"contact-label\">GITHUB</span> <span class=\"contact-sub\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("@DESAI // REPOS")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/about.templ`, Line: 59, Col: 53}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span></div></a> <a href=\"https://t.me/def_desai\" class=\"contact-item\"><div class=\"contact-icon\">TG</div><div><span class=\"contact-label\">TELEGRAM</span> <span class=\"contact-sub\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("@DESAI // DM OPEN")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/about.templ`, Line: 66, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span></div></a> <a href=\"mailto:fodbog@gmail.com\" class=\"contact-item\"><div class=\"contact-icon\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs("@")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/about.templ`, Line: 70, Col: 38}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div><span class=\"contact-label\">EMAIL</span> <span class=\"contact-sub\">FODBOG@GMAIL.COM</span></div></a></div></div></div></section><!-- Stack detail --><div class=\"about-detail-wrap\"><div class=\"about-detail\"><div class=\"sec-label\"><span class=\"sec-num\">01</span> <span class=\"sec-title\">ЭТОТ САЙТ</span><div class=\"sec-line\"></div></div><p class=\"about-detail-text\">Написан на <strong>Go</strong> + <strong>HTMX</strong> + <strong>Templ</strong>. Посты — Markdown-файлы в папке <code>data/posts/</code>. Деплой — один бинарник. Никакого JavaScript-фреймворка. Никакой базы данных. Просто файлы и Go.</p><div style=\"margin-top:1.5rem;\"><a href=\"/\" class=\"btn-primary\" hx-get=\"/\" hx-target=\"#content\" hx-push-url=\"true\">ЧИТАТЬ БЛОГ</a></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
